<?php
if (!defined('BASEPATH'))
	exit('No direct script access allowed');
class vhisSaso2_model extends CI_Model {
public function get_vhis32_data($datefrom,$dateto,$siteid,$skillid,$serviceid){
	$siteid = rtrim($siteid,","); $temp = explode(",",$siteid); $siteid = "'" . implode ( "', '", $temp ) . "'"; $skillid = rtrim($skillid,","); $serviceid = rtrim($serviceid,",");
	$cmd = "declare @FromDateTime datetime = '".  $datefrom   ."', @ToDateTime datetime = '".  $dateto  ."';
				with handled_agent_site as ( select  distinct acdCallDetail.SeqNum as seqnum, dateadd(hour, 8, dateadd(minute, datediff(minute, 0, dateadd(minute, 0, acdCallDetail.CallStartDt)) / 15 * 15, 0)) as handled_interval, acdCallDetail.CallStartDt as callstartdt, acdCallDetail.CallId as callid, acdCallDetail.CallTypeId, acdCallDetail.CallActionId as callactionid,
					acdCallDetail.User_Id as [user_id], acdCallDetail.Station as station, acdCallDetail.Service_Id as service_id, [service].Service_c, acdCallDetail.CallQStartDt, acdCallDetail.QueueStartDt as queuestartdt, acdCallDetail.QueueEndDt as queueenddt, acdCallDetail.WrapEndDt as wrapenddt, isnull(sites.SiteName, 'MOC') as SiteName from RepDb..ACDCallDetail acdCallDetail
					left join [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].[Service] [service]  	on acdCallDetail.Service_Id = [service].Service_Id left join RepUIDB..Stations stations on acdCallDetail.Station = stations.Station left join RepUIDB..Sites sites on stations.SiteGuid = sites.SiteGuid  where dateadd(hour, 8, acdCallDetail.CallStartDt) >= dateadd(d, 0, @FromDateTime) and  dateadd(hour, 8, acdCallDetail.CallStartDt) <= dateadd(d, 0, @ToDateTime) and CallActionId in (8,3, 5, 6 ) and acdCallDetail.CallQStartDt is not null )
				, base_table_vhis28 as ( select acdCallDetail.SeqNum as seqnum, dateadd(hour, 8, dateadd(minute, datediff(minute, 0, dateadd(minute, 0, acdCallDetail.CallStartDt)) / 15 * 15, 0)) as FifteenMinuteInterval, acdCallDetail.CallStartDt as callstartdt, acdCallDetail.CallId as callid, datediff(second, dateadd(hour,8,ACDCallDetail.QueueStartDt), dateadd(hour,8,ACDCallDetail.QueueEndDt)) as AnswerDelay ,case when datediff(second, ACDCallDetail.QueueStartDt, ACDCallDetail.QueueEndDt) > 20 THEN 1 else 0 end as SkillsetAnsAfterThreshold, acdCallDetail.CallTypeId as calltypeid, acdCallDetail.CallActionId as callactionid,
					acdCallDetail.User_Id as [user_id], acdCallDetail.Station as station, acdCallDetail.Service_Id as service_id, (select Service_c from [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].[Service] where Service_Id = acdCallDetail.Service_Id) as servicename, acdCallDetail.CallQStartDt as callqstartdt, acdCallDetail.QueueStartDt as queuestartdt, acdCallDetail.QueueEndDt as queueenddt, acdCallDetail.WrapEndDt as wrapenddt, acdCallDetail.sitename as SiteName
					,isnull(skills.Skill_Id, case acdCallDetail.Service_Id when 4000013 then 4000019 when 4000018 then 4000019 when 4000019 then 4000023 when 4000020 then 4000023 when 4000027 then 4000050 when 4000028 then 4000050 when 4000029 then 4000051 when 4000030 then 4000051 when 4000021 then 4000044 when 4000022 then 4000044 when 4000023 then 4000049 when 4000024 then 4000049 when 4000025 then 4000048 when 4000026 then 4000048 end )as skill_id
					,isnull(skills.Skill_Desc, case acdCallDetail.Service_Id when 4000013 then 'Res_Customer_Assist_sk' when 4000018 then 'Res_Customer_Assist_sk' when 4000019 then 'Biz_Customer_Assist_sk' when 4000020 then 'Biz_Customer_Assist_sk' when 4000027 then 'Cxe_Customer_Assist_sk' when 4000028 then 'Cxe_Customer_Assist_sk' when 4000029 then 'Dpa_Customer_Assist_sk' when 4000030 then 'Dpa_Customer_Assist_sk' when 4000021 then 'Pres_Customer_Assist_sk' when 4000022 then 'Pres_Customer_Assist_sk' when 4000025 then 'Gov_Customer_Assist_sk' when 4000026 then 'Gov_Customer_Assist_sk' when 4000024 then 'Kwatch_Customer_Assist_sk' when 4000023 then 'Kwatch_Customer_Assist_sk' end ) as Skill_Desc
					,isnull(asbr.AgentSkillLevel, 10) as AgentSkillLevel ,service_c from handled_agent_site acdCallDetail
					left join REPDB.[dbo].[ASBRCallSkillDetail] asbr on acdCallDetail.[SeqNum] = asbr.[SeqNum] AND asbr.[Skill_Id] not in (4000001, 4000002) left join [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].Skills skills on asbr.Skill_Id = skills.Skill_Id )
				, base_agent_Count as ( select distinct dateadd(hour,8,a.callstartdt) as CallStartDt ,dateadd(hour,8,b.logindt) as LoginDt ,dateadd(hour,8,b.logoutdt) as LogoutDt ,b.User_Id as Online ,a.Service_Id ,aa.Station ,aa.ModifiedDt ,st.SiteName ,a.CallActionId ,m.Param15 ,b.User_Id ,asbr.AgentSkillLevel from repdb.dbo.ACDCallDetail a 
					left join  repdb.dbo.AgentLoginLogout b on a.Service_Id = b.Service_Id and dateadd(hour,8,a.callstartdt) between dateadd(hour,8,b.logindt)  and dateadd(hour,8,b.LogoutDt) left join repdb.dbo.MediaDataDetail m on b.Service_Id = m.Service_Id and dateadd(hour,8,a.callstartdt) = dateadd(hour,8,m.callstartdt) and m.SeqNum = a.SeqNum and m.CallId = a.CallId
					left join repdb.dbo.AgentStateAudit aa on b.User_Id = aa.User_Id and DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0,b.LoginDt)) / 1 * 1, 0))  = DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0,aa.ModifiedDt)) / 1 * 1, 0))  left join RepUIDB.dbo.Stations s on aa.Station = s.Station left join RepUIDB.dbo.Sites st on s.SiteGuid = st.SiteGuid and aa.Agent_Index is not null
					left join [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].[Service] service on service.Service_Id = a.Service_Id left join repdb.dbo.ASBRCallSkillDetail asbr on asbr.SeqNum = a.SeqNum and asbr.CallId = a.CallId and asbr.CallStartDt = a.CallStartDt where a.Service_Id IN (" . $serviceid . ") and a.CallActionId in (5, 6, 18) and asbr.AgentSkillLevel = 0 )
				, table_2 as ( select distinct dateadd(hour,8,a.callstartdt) as CallStartDt ,dateadd(hour,8,b.logindt) as LoginDt ,dateadd(hour,8,b.logoutdt) as LogoutDt ,b.User_Id as Online ,a.Service_Id ,a.CallActionId ,m.Param15 ,st.SiteName as DNIS_SiteTagging from repdb.dbo.ACDCallDetail a
					left join  repdb.dbo.AgentLoginLogout b on a.Service_Id = b.Service_Id and dateadd(hour,8,a.callstartdt) between dateadd(hour,8,b.logindt)  and dateadd(hour,8,b.LogoutDt) left join repdb.dbo.MediaDataDetail m on m.CallStartDt = a.CallStartDt
					left join RepUIDB.dbo.DNIS D on d.DNIS = m.Param15 left join RepUIDB.dbo.Sites st on d.SiteGuid = st.SiteGuid left join [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].[Service] service on service.Service_Id = a.Service_Id where a.Service_Id IN (" . $serviceid . ") and a.CallActionId in (5, 6, 18) )
				, online_agent_perStation as ( select distinct DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, callstartDt)) / 15 * 15, 0) as FifteenMinuteInterval ,CallStartDt ,count(distinct Online) as Count ,SiteName as StationOnline ,Service_Id ,CallActionId ,Param15 ,AgentSkillLevel from base_agent_Count
					group by DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, callstartDt)) / 15 * 15, 0) ,SiteName  ,Service_Id ,CallActionId ,Param15 ,CallStartDt ,AgentSkillLevel )
				, DNIS_tagging as ( select distinct DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, callstartDt)) / 15 * 15, 0) as FifteenMinuteInterval ,DNIS_SiteTagging as DNIS_Site ,Service_Id ,CallActionId ,Param15 From table_2 )
				, final_query_abandoned as ( select distinct a.FifteenMinuteInterval ,a.Count as AgentLoginCount ,a.Service_Id ,a.CallActionId ,a.StationOnline ,a.callstartdt ,b.DNIS_Site ,case when a.Count = 0 then 'MOC' when a.StationOnline != b.DNIS_Site then 'MOC' else b.DNIS_Site end as SiteName ,a.AgentSkillLevel from online_agent_perStation a
					left join  DNIS_tagging b on a.Service_Id = b.Service_Id and a.FifteenMinuteInterval = b.FifteenMinuteInterval and a.Param15 = b.Param15 )
				, base_online_agents_perInterval as ( select FifteenMinuteInterval ,count(distinct user_id) as Online ,AgentSkillLevel ,Service_Id ,Skill_Id ,SiteName from base_table_vhis28
					group by  AgentSkillLevel ,FifteenMinuteInterval ,Service_Id ,Skill_Id ,SiteName )
				, novice_online as ( select FifteenMinuteInterval ,Online as Online_Novice ,AgentSkillLevel ,Service_Id ,Skill_Id from base_online_agents_perInterval where AgentSkillLevel = 2 )
				, devExpert_online as ( select FifteenMinuteInterval ,Online as Online_DevExpert ,AgentSkillLevel ,Service_Id ,Skill_Id from base_online_agents_perInterval where AgentSkillLevel = 6 )
				, expert_online as ( select FifteenMinuteInterval ,Online as Online_Expert ,AgentSkillLevel ,Service_Id ,Skill_Id from base_online_agents_perInterval where AgentSkillLevel = 10 )
				, calls_offered_table as ( select  count(distinct seqNum) as Offered ,FifteenMinuteInterval ,CallStartDt ,Service_Id ,service_c ,AgentSkillLevel ,Skill_Id ,Skill_Desc ,CallActionId ,siteName ,user_id from  base_table_vhis28
					group by  FifteenMinuteInterval ,Service_Id ,AgentSkillLevel ,Skill_Id ,Skill_Desc ,CallActionId ,CallStartDt ,service_c ,siteName ,user_id )
				, expert_offered as ( select Offered ,FifteenMinuteInterval ,CallStartDt ,Service_Id ,service_c ,AgentSkillLevel ,Skill_Id ,Skill_Desc ,CallActionId ,siteName ,user_id from calls_offered_table where AgentSkillLevel IN (0,10) )
				, calls_answered_table_Group as ( select FifteenMinuteInterval ,CallStartDt ,count(distinct seqNum) as Answered ,datediff(second, queueStartDt, queueEndDt) as AnswerDelay ,datediff(second, QueueEndDt, WrapEndDt) as HandlingTime ,user_id ,QueueStartDt ,QueueEndDt ,WrapEndDt ,Service_Id ,AgentSkillLevel ,Skill_Id ,CallActionId ,service_c ,Skill_Desc ,SiteName from base_table_vhis28
					where AgentSkillLevel != 0 group by FifteenMinuteInterval ,user_id ,Service_Id ,AgentSkillLevel ,Skill_Id ,SiteName ,Skill_Desc ,CallActionId ,CallStartDt ,QueueStartDt ,QueueEndDt ,service_c ,Skill_Desc ,WrapEndDt )
				, calls_offered_group as ( select FifteenMinuteInterval ,sum(Offered) as Offered ,AgentSkillLevel ,Service_Id ,Service_c ,Skill_Id ,Skill_Desc ,siteName ,CallStartDt ,user_id from calls_offered_table
					group by FifteenMinuteInterval ,AgentSkillLevel ,Service_Id ,Service_c ,Skill_Id ,Skill_Desc ,siteName ,user_id ,CallStartDt )
				, answered_group as ( select FifteenMinuteInterval ,Answered ,sum(AnswerDelay) as AnswerDelay_Group ,sum(HandlingTime) as HandlingTime_Group ,sum(case when AnswerDelay <= 20 then 1 else 0 end) as WithinThreshold ,AgentSkillLevel ,user_id ,Service_Id ,Service_c ,Skill_Id ,Skill_Desc ,SiteName ,CallStartDt from calls_answered_table_Group
					group by FifteenMinuteInterval ,AgentSkillLevel ,Service_Id ,Service_c ,SiteName ,Skill_Id ,Skill_Desc ,user_id ,Answered ,CallStartDt )
				, answered_Group_With_Avg as ( select FifteenMinuteInterval ,Answered ,AnswerDelay_Group as ASA_Group ,HandlingTime_Group as AHT_Group ,WithinThreshold ,AgentSkillLevel ,Service_Id ,Service_c ,Skill_Id ,Skill_Desc ,SiteName ,User_Id ,CallStartDt from answered_group )
				, calls_answered_with_Novice as ( select distinct FifteenMinuteInterval ,Answered ,AnswerDelay as AnswerDelay_Novice ,HandlingTime as HandlingTime_Novice ,AgentSkillLevel ,Service_Id ,Service_c ,Skill_Id ,Skill_Desc ,User_Id ,SiteName ,CallStartDt from calls_answered_table_Group where AgentSkillLevel = 2 )
				, calls_answered_with_DevExpert as ( select distinct FifteenMinuteInterval ,Answered ,AnswerDelay as AnswerDelay_DevExpert ,HandlingTime as HandlingTime_DevExpert ,AgentSkillLevel ,Service_Id ,Service_c ,Skill_Id ,Skill_Desc ,User_Id ,SiteName ,CallStartDt from calls_answered_table_Group where AgentSkillLevel = 6 )
				, calls_answered_with_Expert as ( select distinct FifteenMinuteInterval ,Answered ,AnswerDelay as AnswerDelay_Expert ,HandlingTime as HandlingTime_Expert ,AgentSkillLevel ,Service_Id ,Service_c ,Skill_Id ,Skill_Desc ,User_Id ,SiteName ,CallStartDt from calls_answered_table_Group where AgentSkillLevel = 10 )
				, novice_group as ( select  FifteenMinuteInterval ,sum(Answered) as Answered  ,sum(AnswerDelay_Novice) as AnswerDelay_Novice ,sum(HandlingTime_Novice) as HandlingTime_Novice ,AgentSkillLevel ,Service_Id ,service_c ,Skill_Id ,Skill_Desc ,User_Id ,SiteName ,CallStartDt from  calls_answered_with_Novice
					group by FifteenMinuteInterval ,AgentSkillLevel ,Service_Id ,service_c ,Skill_Id ,Skill_Desc ,SiteName ,User_Id ,CallStartDt )
				, novice_group_with_AVG as ( select FifteenMinuteInterval ,Answered ,AnswerDelay_Novice as ASA_Novice ,HandlingTime_Novice as AHT_Novice ,AgentSkillLevel ,Service_Id ,Service_c ,Skill_Id ,Skill_Desc ,User_Id ,SiteName ,CallStartDt from novice_group )
				, devExpert_group as ( select  FifteenMinuteInterval ,sum(Answered) as Answered ,sum(AnswerDelay_DevExpert) as AnswerDelay_DevExpert ,sum(HandlingTime_DevExpert) as HandlingTime_DevExpert ,AgentSkillLevel ,Service_Id ,service_c ,Skill_Id ,Skill_Desc ,User_Id ,SiteName ,callstartdt from calls_answered_with_DevExpert
					group by FifteenMinuteInterval ,AgentSkillLevel ,Service_Id ,service_c ,SiteName ,Skill_Id ,User_Id ,Skill_Desc ,callstartdt )
				, devExpert_group_with_AVG as ( select FifteenMinuteInterval ,Answered ,AnswerDelay_DevExpert as ASA_DevExpert ,HandlingTime_DevExpert as AHT_DevExpert ,AgentSkillLevel ,Service_Id ,Service_c ,Skill_Id ,Skill_Desc ,User_Id ,SiteName ,callstartDt from devExpert_group )
				, expert_group as ( select  FifteenMinuteInterval ,sum(Answered) as Answered ,sum(AnswerDelay_Expert) as AnswerDelay_Expert ,sum(HandlingTime_Expert) as HandlingTime_Expert ,AgentSkillLevel ,Service_Id ,service_c ,Skill_Id ,Skill_Desc ,SiteName ,User_Id ,CallStartDt from  calls_answered_with_Expert
					group by FifteenMinuteInterval ,AgentSkillLevel ,SiteName ,Service_Id ,service_c ,Skill_Id ,Skill_Desc ,User_Id ,CallStartDt )
				, Expert_group_with_AVG as ( select FifteenMinuteInterval ,Answered ,AnswerDelay_Expert as ASA_Expert ,HandlingTime_Expert as AHT_Expert ,AgentSkillLevel ,Service_Id ,SiteName ,Service_c ,Skill_Id ,CallStartDt ,Skill_Desc ,User_Id from Expert_group )
				, base_AgentLogin_Count as ( select distinct dateadd(hour, 8 ,a.callstartdt) as CallStartDt ,dateadd(hour,8,b.logindt) as LoginDt ,dateadd(hour,8,b.logoutdt) as LogoutDt ,b.User_Id as Online ,a.Service_Id ,aa.Station ,aa.ModifiedDt ,st.SiteName ,a.CallActionId ,b.User_Id ,sl.Amount ,sl.Skill_Id ,sl.Level_Id ,sl.Description ,asbr.AgentSkillLevel from repdb.dbo.AgentLoginLogout b
					left join  repdb.dbo.ACDCallDetail a  on a.Service_Id = b.Service_Id and dateadd(hour,8,a.callstartdt) between dateadd(hour,8,b.logindt)  and dateadd(hour,8,b.LogoutDt) left join repdb.dbo.AgentStateAudit aa on b.User_Id = aa.User_Id and DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0,b.LoginDt)) / 1 * 1, 0))  = DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0,aa.ModifiedDt)) / 1 * 1, 0))  and aa.Agent_Index is not null
					left join RepUIDB.dbo.Stations s on aa.Station = s.Station left join RepUIDB.dbo.Sites st on s.SiteGuid = st.SiteGuid left join [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].[Service] service on service.Service_Id = a.Service_Id
					left join [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].Agent_Skills ASK on ask.User_Id = b.User_Id left join [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].Skill_Levels SL on sl.Skill_Id = ask.Skill_Id and sl.Level_Id = ask.Level_Id left join repdb.dbo.ASBRCallSkillDetail asbr on asbr.Service_Id = a.Service_Id and dateadd(hour,8,asbr.callstartdt) between dateadd(hour,8,b.logindt)  and dateadd(hour,8,b.LogoutDt) where a.Service_Id IN (" . $serviceid . ") and a.CallActionId in (8, 18, 5, 6) and ask.Skill_Id not in (4000001, 4000002) )
				, filtered_AgentLogin_Count as ( select  DATEADD(HOUR, 0, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0,CallStartDt)) / 15 * 15, 0)) as FifteenMinuteInterval ,Count(distinct User_Id) as Count_Login ,Service_Id ,Station ,SiteName ,CallActionId ,Amount ,Skill_Id ,Level_Id ,Description ,user_id ,agentskillLevel from base_AgentLogin_Count
					group by CallStartDt ,Service_Id ,Station ,SiteName ,CallActionId ,Amount ,Skill_Id ,Level_Id ,Description ,user_id ,agentskillLevel) 
				, grouped_Online as ( select FifteenMinuteInterval ,count(distinct Count_Login) as Count_Login ,(case when amount = 2 then 1 end) as Online_Novice ,(case when amount = 6 then 1 end) as Online_DevExpert ,(case when amount = 10 then 1 end) as Online_Expert ,Service_Id ,SiteName ,Skill_Id ,user_id ,description ,agentskillLevel from  filtered_AgentLogin_Count
					group by FifteenMinuteInterval ,Service_Id ,SiteName ,Skill_Id ,amount ,user_id ,Description ,agentskillLevel )
				,grouped_Online_Final as ( select  FifteenMinuteInterval ,Count(distinct Count_Login) as Count_Login ,Count(distinct Online_Novice) as Online_Novice ,Count(distinct Online_DevExpert) as Online_DevExpert ,Count(distinct Online_Expert) as Online_Expert ,user_id ,Service_Id ,SiteName ,Skill_Id ,description ,AgentSkillLevel from grouped_Online
					where AgentSkillLevel IN (2,6,10) group by FifteenMinuteInterval ,Service_Id  ,SiteName ,Skill_Id ,user_id ,description ,AgentSkillLevel )
				, group_Online_FInal_Abandoned as ( select distinct FifteenMinuteInterval ,Count(distinct Count_Login) as Count_Login ,Count(distinct Online_Novice) as Online_Novice ,Count(distinct Online_DevExpert) as Online_DevExpert ,Count(distinct Online_Expert) as Online_Expert ,user_id ,Service_Id ,SiteName ,Skill_Id ,description ,AgentSkillLevel from grouped_Online
					where agentskillLevel = 0 group by FifteenMinuteInterval ,Service_Id ,SiteName ,Skill_Id ,user_id ,description ,AgentSkillLevel )
				,base_AgentLogin_Count_with_Skill_Level as ( Select distinct dateadd(hour, 8 ,acd.CallStartDt) as CallStartDt ,acd.Service_Id ,asbr.Skill_Id ,asbr.AgentSkillLevel ,agt.User_Id ,(select top 1 level_id from [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].Agent_SkillsAudit aa  where aa.user_id = agt.User_Id and aa.Skill_Id = asbr.Skill_Id and aa.ModifiedDt <= acd.CallStartDt and aa.ModifiedDt <= agt.LoginDt order by ModifiedDt desc) as level_id ,aa.Station ,st.SiteName from  REPDB.dbo.ACDCallDetail acd
					left join REPDB..AgentLoginLogout agt on (acd.CallStartDt between agt.LoginDt and agt.LogoutDt or acd.CallStartDt >= agt.LoginDt and agt.LogoutDt is null) left join REPDB..ASBRCallSkillDetail asbr on acd.SeqNum = asbr.SeqNum and acd.Service_Id = asbr.Service_Id
					left join repdb.dbo.AgentStateAudit aa on agt.User_Id = aa.User_Id and DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0,agt.LoginDt)) / 1 * 1, 0))  = DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0,aa.ModifiedDt)) / 1 * 1, 0))  and aa.Agent_Index is not null left join RepUIDB.dbo.Stations s on aa.Station = s.Station left join RepUIDB.dbo.Sites st on s.SiteGuid = st.SiteGuid where acd.Service_Id IN (" . $serviceid . ") and asbr.Skill_Id not in (4000001, 4000002) )
				, base_table_skill_levels as ( select  * from [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].[Skill_Levels] SKL )
				, agent_login_with_Skill_Description_Answered as ( select  DATEADD(HOUR, 0, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0,CallStartDt)) / 15 * 15, 0)) as FifteenMinuteInterval ,Service_Id ,User_Id ,a.Skill_Id ,AgentSkillLevel ,a.level_id ,b.description ,a.SiteName ,a.CallStartDt from base_AgentLogin_Count_with_Skill_Level a 
					left join base_table_skill_levels b on a.Skill_Id = b.Skill_Id and a.level_id = b.Level_Id where AgentSkillLevel IN (2,6,10) )
				, agent_login_with_Skill_Description_Abandoned as ( select DATEADD(HOUR, 0, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0,CallStartDt)) / 15 * 15, 0)) as FifteenMinuteInterval ,Service_Id ,User_Id ,a.Skill_Id ,AgentSkillLevel ,a.level_id ,b.description ,a.SiteName ,a.CallStartDt from base_AgentLogin_Count_with_Skill_Level a
					LEFT join base_table_skill_levels b on a.Skill_Id = b.Skill_Id and a.level_id = b.Level_Id where AgentSkillLevel NOT IN (2,6,10) )
				, final_query as ( select  a.FifteenMinuteInterval ,a.SiteName as Site ,i.SiteName as SiteNameDNIS ,COALESCE(a.SiteName, i.siteName) as SiteName ,a.Offered ,b.Answered ,c.Answered as NoviceAnswered ,d.Answered as DevExpertAnswered ,e.Answered as ExpertAnswered ,b.WithinThreshold ,b.ASA_Group ,b.AHT_Group ,c.ASA_Novice ,c.AHT_Novice ,d.ASA_DevExpert
					,d.AHT_DevExpert ,e.ASA_Expert ,e.AHT_Expert ,a.AgentSkillLevel ,a.Service_Id ,a.Service_c ,a.Skill_Id ,a.Skill_Desc ,a.User_Id ,a.CallStartDt ,a.CallActionId ,case when a.AgentSkillLevel = 2 then 1 else 0 end as Novice_Offered ,case when a.AgentSkillLevel = 6 then 1 else 0 end as DevExpert_Offered ,case when a.AgentSkillLevel = 10 then 1 else 0 end as Expert_Offered from calls_offered_table a
					left join  answered_Group_With_Avg b on a.FifteenMinuteInterval = b.FifteenMinuteInterval and a.Service_Id = b.Service_Id and a.Skill_Id = b.Skill_Id and a.AgentSkillLevel = b.AgentSkillLevel and a.User_Id = b.User_Id and a.SiteName = b.SiteName and b.CallStartDt = a.CallStartDt
					left join  novice_group_with_AVG C on a.FifteenMinuteInterval = c.FifteenMinuteInterval and a.Service_Id = c.Service_Id and a.Skill_Id = c.Skill_Id and a.AgentSkillLevel = c.AgentSkillLevel and a.User_Id = c.User_Id and a.SiteName = c.SiteName and c.CallStartDt = a.CallStartDt left join  devExpert_group_with_AVG D on a.FifteenMinuteInterval = d.FifteenMinuteInterval and a.Service_Id = d.Service_Id and a.Skill_Id = d.Skill_Id and a.AgentSkillLevel = d.AgentSkillLevel and a.User_Id = d.User_Id and a.SiteName = d.SiteName and d.CallStartDt = a.CallStartDt
					left join Expert_group_with_AVG E on a.FifteenMinuteInterval = e.FifteenMinuteInterval and a.Service_Id = e.Service_Id and a.Skill_Id = e.Skill_Id and a.AgentSkillLevel = e.AgentSkillLevel and a.User_Id = e.User_Id and a.SiteName = e.SiteName and e.CallStartDt = a.CallStartDt left join  final_query_abandoned i on i.FifteenMinuteInterval = a.FifteenMinuteInterval and i.Service_Id = a.Service_Id and i.AgentSkillLevel = a.AgentSkillLevel and i.CallStartDt = a.CallStartDt )
				, finished_query as ( select DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 15, DATEADD(HOUR, 8, a.callstartdt))) / 15 * 15, 0) as 'Interval',  DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.callstartdt)) / 15 * 15, 0)) as '15MinsInterval',
					DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.callstartdt)) / 30 * 30, 0)) as '30MinsInterval', DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.callstartdt)) / 60 * 60, 0)) as '60MinsInterval',
					CONVERT(VARCHAR(20), (dateadd(dd, 0 - (@@datefirst +6 + datepart(dw, dateadd(HOUR, 8,a.callstartdt))) %7 , dateadd(HOUR, 8,a.callstartdt))), 101) as Sunday, CONVERT(VARCHAR(20), (dateadd(dd, 6 - (@@datefirst +6 + datepart(dw, dateadd(HOUR, 8,a.callstartdt))) %7 , dateadd(HOUR, 8,a.callstartdt))), 101) as Saturday,
					convert(varchar(10), dateadd(HOUR, 8,a.callstartdt), 101) + ' ' + format(CAST(DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.callstartdt)) / 15 * 15, 0)) as Datetime), 'hh:mm tt') as Minus15Mins,
					convert(varchar(10), dateadd(HOUR, 8,a.callstartdt), 101) + ' ' + format(CAST(DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.callstartdt)) / 30 * 30, 0)) as Datetime), 'hh:mm tt') as Minus30Mins,
					convert(varchar(10), dateadd(HOUR, 8,a.callstartdt), 101) + ' ' + format(CAST(DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.callstartdt)) / 60 * 60, 0)) as Datetime), 'hh:mm tt') as Minus60Mins,
					datepart(wk, dateadd(HOUR, 8, a.callstartdt)) as Week_count, datepart(w, dateadd(HOUR, 8, a.callstartdt)) as Day_Count,  datename(dw, dateadd(HOUR, 8, a.callstartdt)) as Day_Name, convert(varchar(10), dateadd(HOUR, 8,a.callstartdt), 101) as perDate, DATEPART(M, DATEADD(HOUR, 8, a.callstartdt)) AS Month_Count,
					cast(datename(m, dateadd(hour,8,a.callstartdt)) as varchar(10)) + ', ' + cast(year(dateadd(hour,8,a.callstartdt)) as varchar(10)) AS MONTH_NAME, cast(year(dateadd(hour,8,a.callstartdt)) as varchar(10)) + ', ' + cast(datename(m, dateadd(hour,8,a.callstartdt)) as varchar(10)) as Year_Month, YEAR(DATEADD(HOUR, 8, a.callstartdt)) AS YEAR, DATEADD(HOUR, 8, a.callstartdt) AS DATE_TIME,
					convert(varchar(10), dateadd(HOUR, 8,a.callstartdt), 101) +' '+ case when datepart(hour, dateadd(HOUR, 8, a.callstartdt)) <= 5 or datepart(hour, dateadd(HOUR, 8, a.callstartdt)) >= 22 then '10PM - 6AM' end as Graveyard,
					convert(varchar(10), dateadd(HOUR, 8,a.callstartdt), 101) +' '+ case when datepart(hour, dateadd(HOUR, 8, a.callstartdt)) > = 14 and datepart(hour, dateadd(HOUR, 8, a.callstartdt)) <= 21 then '2PM - 10PM'  end as Afternoon,
					convert(varchar(10), dateadd(HOUR, 8,a.callstartdt), 101) +' '+ case when datepart(hour, dateadd(HOUR, 8, a.callstartdt)) >= 6 and datepart(hour, dateadd(HOUR, 8, a.callstartdt)) <= 13 then '6AM - 2PM' end as Morning 		
					,a.FifteenMinuteInterval ,a.SiteName ,a.Offered ,isnull(a.Answered, 0) as Answered ,a.Novice_Offered ,a.DevExpert_Offered ,a.Expert_Offered ,a.NoviceAnswered ,a.DevExpertAnswered ,a.ExpertAnswered ,a.WithinThreshold ,a.ASA_Group ,a.AHT_Group ,a.ASA_Novice ,a.AHT_Novice ,a.ASA_DevExpert ,a.AHT_DevExpert ,a.ASA_Expert ,a.AHT_Expert ,0 as _online ,fla.User_Id as AnsUser_Id
					,aban.User_Id as AbanUser_id ,COALESCE(fla.User_Id, aban.User_Id) as User_ID ,aban.Description as Description_aban ,fla.Description as Description_Answered ,COALESCE(fla.description, aban.Description) as Description ,a.AgentSkillLevel ,a.Service_Id ,a.Service_c ,a.Skill_Id ,a.Skill_Desc ,Expert_Offered + case when a.ExpertAnswered is null then 0 else a.ExpertAnswered end as Offered_Expert ,a.CallActionId from final_query a
					left join agent_login_with_Skill_Description_Answered FLA on a.FifteenMinuteInterval = FLA.FifteenMinuteInterval and a.Skill_Id = fla.Skill_Id and a.Service_Id = fla.Service_Id and a.SiteName = fla.SiteName and a.User_Id = fla.User_Id and a.CallStartDt = fla.CallStartDt
					left join  agent_login_with_Skill_Description_Abandoned Aban on a.FifteenMinuteInterval = Aban.FifteenMinuteInterval and a.Skill_Id = Aban.Skill_Id and a.Service_Id = Aban.Service_Id and a.SiteName = Aban.SiteName and a.AgentSkillLevel = aban.AgentSkillLevel and a.callstartdt = aban.callstartdt )
				select fq.* from finished_query fq where service_id in (" . $serviceid . ")  and skill_id in (" . $skillid . ") and CallActionId <> 18 and fq.Answered is not null and fq.Answered =1 and  SiteName IN (" . $siteid .") and FifteenMinuteInterval >= '".  $datefrom   ."' and FifteenMinuteInterval <= '".  $dateto  ."'
			UNION ALL
				SELECT * FROM ( select  DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 15, DATEADD(HOUR, 8, a.CallStartDt))) / 15 * 15, 0) as 'Interval', DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.CallStartDt)) / 15 * 15, 0)) as '15MinsInterval', DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.CallStartDt)) / 30 * 30, 0)) as '30MinsInterval', DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.CallStartDt)) / 60 * 60, 0)) as '60MinsInterval',
					CONVERT(VARCHAR(20), (dateadd(dd, 0 - (@@datefirst +6 + datepart(dw, dateadd(hour, 8,a.CallStartDt))) %7 , dateadd(hour, 8,a.CallStartDt))), 101) as Sunday, CONVERT(VARCHAR(20), (dateadd(dd, 6 - (@@datefirst +6 + datepart(dw, dateadd(hour, 8,a.CallStartDt))) %7 , dateadd(hour, 8,a.CallStartDt))), 101) as Saturday,
					convert(varchar(10), dateadd(hour, 8,a.CallStartDt), 101) + ' ' + format(CAST(DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.CallStartDt)) / 15 * 15, 0)) as Datetime), 'hh:mm tt') as Minus15Mins,
					convert(varchar(10), dateadd(hour, 8,a.CallStartDt), 101) + ' ' + format(CAST(DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.CallStartDt)) / 30 * 30, 0)) as Datetime), 'hh:mm tt') as Minus30Mins,
					convert(varchar(10), dateadd(hour, 8,a.CallStartDt), 101) + ' ' + format(CAST(DATEADD(HOUR, 8, DATEADD(MINUTE, DATEDIFF(MINUTE, 0, DATEADD(MINUTE, 0, a.CallStartDt)) / 60 * 60, 0)) as Datetime), 'hh:mm tt') as Minus60Mins,
					datepart(wk, dateadd(hour, 8, a.CallStartDt)) as Week_count, datepart(w, dateadd(hour, 8, a.CallStartDt)) as Day_Count,  datename(dw, dateadd(hour, 8, a.CallStartDt)) as Day_Name, convert(varchar(10), dateadd(hour, 8,a.CallStartDt), 101) as perDate, DATEPART(M, DATEADD(HOUR, 8, a.CallStartDt)) AS Month_Count,
					cast(datename(m, dateadd(hour,8,a.CallStartDt)) as varchar(10)) + ', ' + cast(year(dateadd(hour,8,a.CallStartDt)) as varchar(10)) AS MONTH_NAME, cast(year(dateadd(hour,8,a.CallStartDt)) as varchar(10)) + ', ' + cast(datename(m, dateadd(hour,8,a.CallStartDt)) as varchar(10)) as Year_Month, YEAR(DATEADD(HOUR, 8, a.CallStartDt)) AS YEAR, DATEADD(HOUR, 8, a.CallStartDt) AS DATE_TIME,
					convert(varchar(10), dateadd(hour, 8,a.CallStartDt), 101) +' '+ case when datepart(hour, dateadd(hour, 8, a.CallStartDt)) <= 5 or datepart(hour, dateadd(hour, 8, a.CallStartDt)) >= 22 then '10PM - 6AM' end as Graveyard,
					convert(varchar(10), dateadd(hour, 8,a.CallStartDt), 101) +' '+ case when datepart(hour, dateadd(hour, 8, a.CallStartDt)) > = 14 and datepart(hour, dateadd(hour, 8, a.CallStartDt)) <= 21 then '2PM - 10PM'  end as Afternoon,
					convert(varchar(10), dateadd(hour, 8,a.CallStartDt), 101) +' '+ case when datepart(hour, dateadd(hour, 8, a.CallStartDt)) >= 6 and datepart(hour, dateadd(hour, 8, a.CallStartDt)) <= 13 then '6AM - 2PM' end as Morning
					,a.CallStartDt ,isnull(sites.SiteName, 'MOC') as sitename ,'1' as Offered  ,'0' as Answered ,NULL as Novice_Offered ,NULL as DevExpert_Offered ,NULL as Expert_Offered ,NULL as NoviceAnswered ,NULL as DevExpertAnswered ,NULL as ExpertAnswered ,NULL as WithinThreshold ,NULL as ASA_Group
					,NULL as AHT_Group ,NULL as ASA_Novice ,NULL as AHT_Novice ,NULL as ASA_DevExpert ,NULL as AHT_DevExpert ,NULL as ASA_Expert ,NULL as AHT_Expert ,NULL as _online ,NULL as AnsUser_Id ,NULL as AbanUser_id ,NULL as User_ID ,NULL as Description_aban ,NULL as Description_Answered ,NULL as Description ,NULL as AgentSkillLevel ,a.Service_Id as Service_Id ,(SELECT [Service_c] FROM [VW12PCTIDB01\UIP_CONFIG].[config_epro].[dbo].[Service] WHERE Service_Id =a.Service_Id) as Service_c
					, isnull((select top 1 Skill_Id from REPDB..ASBRCallSkillDetail where Service_Id = a.Service_Id and SeqNum = a.SeqNum and  Skill_Id not in (4000001, 4000002)),  case a.Service_Id when 4000013 then 4000019 when 4000018 then 4000019 when 4000019 then 4000023 when 4000020 then 4000023 when 4000027 then 4000050 when 4000028 then 4000050 when 4000029 then 4000051 when 4000030 then 4000051 when 4000021 then 4000044 when 4000022 then 4000044 when 4000023 then 4000049 when 4000024 then 4000049 when 4000025 then 4000048 when 4000026 then 4000048 end )  as skill_id
					,isnull(NULL, case a.Service_Id when 4000013 then 'Res_Customer_Assist_sk' when 4000018 then 'Res_Customer_Assist_sk' when 4000019 then 'Biz_Customer_Assist_sk' when 4000020 then 'Biz_Customer_Assist_sk' when 4000027 then 'Cxe_Customer_Assist_sk' when 4000028 then 'Cxe_Customer_Assist_sk' when 4000029 then 'Dpa_Customer_Assist_sk' when 4000030 then 'Dpa_Customer_Assist_sk' when 4000021 then 'Pres_Customer_Assist_sk' when 4000022 then 'Pres_Customer_Assist_sk' when 4000025 then 'Gov_Customer_Assist_sk' when 4000026 then 'Gov_Customer_Assist_sk' when 4000024 then 'Kwatch_Customer_Assist_sk' when 4000023 then 'Kwatch_Customer_Assist_sk' end ) as Skill_Desc 
					,NULL as Offered_Expert ,a.CallActionId from repdb.dbo.ACDCallDetail a
					left join RepUIDB..Stations stations on a.Station = stations.Station left join RepUIDB..Sites sites on stations.SiteGuid = sites.SiteGuid  where a.User_Id is null and DATEADD(HOUR, 8,a.CallStartDt) >= '".  $datefrom   ."' and DATEADD(HOUR, 8,a.CallStartDt) <= '".  $dateto  ."' and a.CallActionId=5 ) last_tb where service_id in (" . $serviceid . ")  and skill_id in (" . $skillid . ") and  SiteName IN (" . $siteid .") " ;
		$query = $this->db->query($cmd);
	    $output = $query->result();
		return $query;
	}
}